"""create initial tables

Revision ID: 70043fe6862c
Revises:
Create Date: 2026-07-02 15:36:53.872701

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70043fe6862c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("photo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("favorite_sports", sa.JSON(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="experiencelevel"),
            nullable=False,
        ),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "matches",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sport",
            sa.Enum(
                "FOOTBALL", "VOLLEYBALL", "BASKETBALL", "TENNIS", "FUTSAL", "OTHER", name="sport"
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("BEGINNER", "INTERMEDIATE", "ADVANCED", name="experiencelevel"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organizer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "FULL", "PENDING_APPROVAL", "CLOSED", "CANCELLED", name="matchstatus"),
            nullable=False,
        ),
        sa.Column("allow_beginners", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organizer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_organizer_id"), "matches", ["organizer_id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sender_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("type", sa.Enum("MESSAGE", "SYSTEM", name="messagetype"), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_match_id"), "messages", ["match_id"], unique=False)
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "participants",
        sa.Column("match_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "PENDING", "CANCELLED", name="participationstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "user_id"),
    )
    op.create_table(
        "ratings",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rated_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rater_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("punctuality", sa.Integer(), nullable=False),
        sa.Column("respect", sa.Integer(), nullable=False),
        sa.Column("behavior", sa.Integer(), nullable=False),
        sa.Column("presence", sa.Integer(), nullable=False),
        sa.Column("overall", sa.Integer(), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rated_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rater_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ratings_match_id"), "ratings", ["match_id"], unique=False)
    op.create_index(op.f("ix_ratings_rated_user_id"), "ratings", ["rated_user_id"], unique=False)
    op.create_index(op.f("ix_ratings_rater_user_id"), "ratings", ["rater_user_id"], unique=False)
    op.create_table(
        "reports",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reported_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reporter_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("match_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "BAD_BEHAVIOR",
                "VIOLENCE",
                "NO_SHOW",
                "HATE_SPEECH",
                "SPAM",
                "FAKE_INFO",
                "OTHER",
                name="reportreason",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ARCHIVED", "WARNED", "BANNED", name="reportstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_match_id"), "reports", ["match_id"], unique=False)
    op.create_index(
        op.f("ix_reports_reported_user_id"), "reports", ["reported_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_reports_reporter_user_id"), "reports", ["reporter_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reports_reporter_user_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_reported_user_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_match_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_ratings_rater_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_rated_user_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_match_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_table("participants")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_match_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_matches_organizer_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
